name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Make Distribute
        run: |
          make all distribute

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: Distribute/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Distribute/*.zip
          tag: ${{ github.ref }}
          file_glob: true

  analyze-scripts:
    name: Analyze Scripts
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependency
        run: |
          brew install shellcheck

      - name: Run shellcheck
        run: find . \( -name "*.tool" -o -name "*.command" -o -name "*.sh" \) -exec sh -c 'for TargetFile; do shellcheck --severity=info "${TargetFile}" || exit 1; done' sh {} +

  analyze-dsls:
    name: Analyze DSLs
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependency
        run: |
          curl -# -L -O https://raw.githubusercontent.com/Acidanthera/MaciASL/master/Dist/iasl-stable || exit 1
          chmod +x iasl* || exit 1

      - name: Run iasl
        run: |
          find . -name '*.dsl' -exec sh -c './iasl* -vs -p "${1%/*}/../${1##*/}" "${1%}" && echo || exit 1' sh {} \;